timezone: UTC
permalink: pretty
prose:
  metadata:
    "_posts/blog": |
      title:    "Title of your article"
      abstract: "Abstract"
      lang: en
domain: itorres.net
title: Ignacio Torres Masdeu
author: Ignacio Torres Masdeu
email: i@itorres.net
markdown: redcarpet
highlighter: pygments
include: [ .well-known ]
host: 0.0.0.0
kramdown:
  input: GFM
  enable_coderay: true