timezone: UTC
highlighter: rouge
permalink: pretty
prose:
  metadata:
    "_posts/blog": |
      title:    "Title of your article"
      abstract: "Abstract"
      lang: en

domain: ignacio.torresmasdeu.name
title: Ignacio Torres Masdeu
author: Ignacio Torres Masdeu
email: ignacio@torresmasdeu.name
markdown: rdiscount
include: [ .well-known ]
host: 0.0.0.0
