timezone: UTC
pygments: true
permalink: pretty
auto: true
server: true
prose:
  metadata:
    "_posts/blog": |
      title:    "Title of your article"
      abstract: "Abstract"
      lang: en

domain: ignacio.torresmasdeu.name
title: Ignacio Torres Masdeu
author: Ignacio Torres Masdeu
email: ignacio@torresmasdeu.name
